apiVersion: v1
kind: Namespace
metadata:
  name: idwall-ns

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: idwall-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello-idwall.challenge
    http:
      paths:
      - path: /
        backend:
          serviceName: idwall-svc
          servicePort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idwall-app
  namespace: idwall-ns
spec:
  selector:
    matchLabels:
      run: idwall-app
  replicas: 1
  template:
    metadata:
      labels:
        run: idwall-app
    spec:
      containers:
      - name: idwall-app
        image: idwall-app-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3        
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3           
          

---
kind: Service
apiVersion: v1
metadata:
  name: idwall-svc
  namespace: idwall-ns
  labels:
    run: idwall-app
spec:
  selector:
    run: idwall-app
  type: NodePort  
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000