replicaCount: 1

image:
  repository: idwall-app-image
  tag: latest
  pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000

ingress:
  enabled: true
  annotations: 
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: hello-idwall.challenge
      paths: [/]

resources: 
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 500m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
